export const bakeryItems = [
    {
      id: "1",
      img: "./src/croissant.jpg",
      title: "Croissant",
      description: "A flaky and buttery French pastry.",
      price: "$2.50",
      rate: 4.5,
      reviews: 56,
    },
    {
      id: "2",
      img: "./src/baguette.jpg",
      title: "Baguette",
      description: "A classic French bread with a crispy crust.",
      price: "$3.00",
      rate: 4.0,
      reviews: 42,
    },
    {
      id: "3",
      img: "./src/cupcake.jpg",
      title: "Cupcake",
      description: "Delicious cupcakes in various flavors.",
      price: "$2.00",
      rate: 4.8,
      reviews: 65,
    },
    {
      id: "4",
      img: "./src/doughnut.jpg",
      title: "Doughnut",
      description: "Soft and sweet doughnuts with various toppings.",
      price: "$1.50",
      rate: 4.2,
      reviews: 38,
    },
    {
      id: "5",
      img: "./src/apple-pie.jpg",
      title: "Apple Pie",
      description: "Classic apple pie with a buttery crust.",
      price: "$4.50",
      rate: 4.7,
      reviews: 50,
    },
    {
      id: "6",
      img: "./src/cinnamon-roll.jpg",
      title: "Cinnamon Roll",
      description: "Warm and gooey cinnamon rolls with icing.",
      price: "$2.75",
      rate: 4.6,
      reviews: 60,
    },
    {
      id: "7",
      img: "./src/danish-pastry.jpg",
      title: "Danish Pastry",
      description: "Layers of flaky pastry with sweet fillings.",
      price: "$3.25",
      rate: 4.4,
      reviews: 48,
    },
    {
      id: "8",
      img: "./src/chocolate-cake.jpg",
      title: "Chocolate Cake",
      description: "Rich and moist chocolate cake for chocolate lovers.",
      price: "$5.00",
      rate: 4.9,
      reviews: 70,
    },
    {
      id: "9",
      img: "./src/sourdough-bread.jpg",
      title: "Sourdough Bread",
      description: "Artisanal sourdough bread with a chewy crust.",
      price: "$3.50",
      rate: 4.3,
      reviews: 55,
    },
    {
      id: "10",
      img: "./src/blueberry-muffin.jpg",
      title: "Blueberry Muffin",
      description: "Moist and fruity muffins with blueberries.",
      price: "$2.25",
      rate: 4.7,
      reviews: 52,
    },
    {
      id: "11",
      img: "./src/pie.jpg",
      title: "Banana Pie",
      description: "Moist and fruity muffins with blueberries.",
      price: "$2.25",
      rate: 4.7,
      reviews: 52,
    },
    {
      id: "12",
      img: "./src/.jpg",
      title: "Blueberry Muffin",
      description: "Moist and fruity muffins with blueberries.",
      price: "$2.25",
      rate: 4.7,
      reviews: 52,
    },
  ];
  